import { Translations } from './types';

export const translations: Translations = {
  en: {
    headerTitle: 'Artistic Vision AI',
    creatorName: 'Ahmed Abo Al Ezz',
    creatorLink: 'https://www.facebook.com/briefdesign1',
    toggleTheme: 'Toggle light/dark mode',
    pageTitle: 'Turn Any Image into an AI Masterpiece',
    pageSubtitle: 'Get a precise artistic description to reignite your artistic inspiration.',
    uploadAreaTitle: 'Drag & Drop or Click to Upload',
    uploadAreaSubtitle: 'PNG, JPG, WEBP up to 10MB',
    uploadAreaButton: 'Choose File',
    howItWorksTitle: 'A Creative Co-Pilot for Designers',
    step1Title: 'Upload & Refine',
    step1Description: 'Start with an image and add instructions to guide the AI.',
    step2Title: 'In-Depth Analysis',
    step2Description: 'Receive a main prompt, style keywords, and a full color palette.',
    step3Title: 'Create with Insight',
    step3Description: 'Use the detailed analysis to create stunning new visuals.',
    analyzeButton: 'Analyze Image',
    analyzing: 'Analyzing...',
    resultTitle: 'AI Analysis Complete',
    mainPromptTitle: 'Main Artistic Prompt',
    styleKeywordsTitle: 'Style & Keyword Analysis',
    colorPaletteTitle: 'Color Palette',
    alternativePromptsTitle: 'Alternative Descriptions',
    concisePromptTab: 'Concise',
    poeticPromptTab: 'Poetic',
    copyButton: 'Copy',
    copied: 'Copied!',
    footerText: 'Developed by',
    errorTitle: 'An Error Occurred',
    errorInvalidKey: 'The Gemini API key is invalid or not configured correctly.',
    errorGeneric: 'Something went wrong. Please try again later.',
    errorNoImage: 'Please upload an image first.',
    editOptionsTitle: 'Edit Options',
    optionRemoveText: 'Remove text from image',
    optionWhiteBackground: 'Make background white',
    optionBlackBackground: 'Make background black',
    additionalInstructionsTitle: 'Additional Instructions',
    additionalInstructionsPlaceholder: 'e.g., make the sky rainy, change the car color to red...',
    goBackButton: 'Analyze New Image',
  },
  ar: {
    headerTitle: 'الرؤية الفنية بالذكاء الاصطناعي',
    creatorName: 'أحمد أبو العز',
    creatorLink: 'https://www.facebook.com/briefdesign1',
    toggleTheme: 'تبديل الوضع الفاتح/الداكن',
    pageTitle: 'حوّل أي صورة إلى لوحة فنية بالذكاء الاصطناعي',
    pageSubtitle: 'احصل على وصف فني دقيق لإعادة إلهامك الفني.',
    uploadAreaTitle: 'اسحب وأفلت أو انقر للتحميل',
    uploadAreaSubtitle: 'PNG, JPG, WEBP بحجم يصل إلى 10 ميجا بايت',
    uploadAreaButton: 'اختر ملف',
    howItWorksTitle: 'مساعد إبداعي للمصممين',
    step1Title: 'ارفع وعدّل',
    step1Description: 'ابدأ بصورة وأضف تعليمات لتوجيه الذكاء الاصطناعي.',
    step2Title: 'تحليل فني عميق',
    step2Description: 'احصل على وصف رئيسي، كلمات مفتاحية للأسلوب، ولوحة ألوان كاملة.',
    step3Title: 'أبدع ببصيرة فنية',
    step3Description: 'استخدم التحليل المفصل لإنشاء أعمال بصرية مذهلة.',
    analyzeButton: 'تحليل الصورة',
    analyzing: 'جاري التحليل...',
    resultTitle: 'اكتمل تحليل الذكاء الاصطناعي',
    mainPromptTitle: 'الوصف الفني الرئيسي',
    styleKeywordsTitle: 'تحليل الأسلوب والكلمات المفتاحية',
    colorPaletteTitle: 'لوحة الألوان',
    alternativePromptsTitle: 'أوصاف بديلة',
    concisePromptTab: 'موجز',
    poeticPromptTab: 'شاعري',
    copyButton: 'نسخ',
    copied: 'تم النسخ!',
    footerText: 'تم تطويره بواسطة',
    errorTitle: 'حدث خطأ',
    errorInvalidKey: 'مفتاح Gemini API غير صالح أو لم يتم تكوينه بشكل صحيح.',
    errorGeneric: 'حدث خطأ ما. يرجى المحاولة مرة أخرى في وقت لاحق.',
    errorNoImage: 'يرجى رفع صورة أولاً.',
    editOptionsTitle: 'خيارات التعديل',
    optionRemoveText: 'إزالة الكلام من الصورة',
    optionWhiteBackground: 'جعل الخلفية بيضاء',
    optionBlackBackground: 'جعل الخلفية سوداء',
    additionalInstructionsTitle: 'تعليمات إضافية',
    additionalInstructionsPlaceholder: 'مثال: اجعل السماء ممطرة، غير لون السيارة إلى أحمر...',
    goBackButton: 'تحليل صورة جديدة',
  },
  fr: {
    headerTitle: 'Vision Artistique IA',
    creatorName: 'Ahmed Abo Al Ezz',
    creatorLink: 'https://www.facebook.com/briefdesign1',
    toggleTheme: 'Basculer le mode clair/sombre',
    pageTitle: "Transformez n'importe quelle image en chef-d'œuvre IA",
    pageSubtitle: "Obtenez une description artistique précise pour raviver votre inspiration artistique.",
    uploadAreaTitle: 'Glissez-déposez ou cliquez pour télécharger',
    uploadAreaSubtitle: "PNG, JPG, WEBP jusqu'à 10 Mo",
    uploadAreaButton: 'Choisir un fichier',
    howItWorksTitle: 'Un co-pilote créatif pour les designers',
    step1Title: 'Télécharger & Affiner',
    step1Description: "Commencez avec une image et ajoutez des instructions pour guider l'IA.",
    step2Title: 'Analyse Approfondie',
    step2Description: 'Recevez un prompt principal, des mots-clés de style et une palette de couleurs complète.',
    step3Title: 'Créer avec Perspicacité',
    step3Description: "Utilisez l'analyse détaillée pour créer de nouveaux visuels époustouflants.",
    analyzeButton: "Analyser l'image",
    analyzing: 'Analyse en cours...',
    resultTitle: 'Analyse IA terminée',
    mainPromptTitle: 'Prompt Artistique Principal',
    styleKeywordsTitle: 'Analyse de Style & Mots-clés',
    colorPaletteTitle: 'Palette de Couleurs',
    alternativePromptsTitle: 'Descriptions Alternatives',
    concisePromptTab: 'Concis',
    poeticPromptTab: 'Poétique',
    copyButton: 'Copier',
    copied: 'Copié !',
    footerText: 'Développé par',
    errorTitle: 'Une erreur est survenue',
    errorInvalidKey: "La clé API Gemini est invalide ou n'est pas configurée correctement.",
    errorGeneric: "Quelque chose s'est mal passé. Veuillez réessayer plus tard.",
    errorNoImage: "Veuillez d'abord télécharger une image.",
    editOptionsTitle: 'Options d\'édition',
    optionRemoveText: "Supprimer le texte de l'image",
    optionWhiteBackground: "Rendre l'arrière-plan blanc",
    optionBlackBackground: "Rendre l'arrière-plan noir",
    additionalInstructionsTitle: 'Instructions supplémentaires',
    additionalInstructionsPlaceholder: 'ex: rendre le ciel pluvieux, changer la couleur de la voiture en rouge...',
    goBackButton: 'Analyser une nouvelle image',
  },
};